package servent.message;

public enum MessageType {
	NEW_NODE, WELCOME, SORRY, UPDATE, PUT, ASK_GET, TELL_GET, POISON,
	GOODBYE, REMOVE_UPDATE, TOKEN, REQUEST, CONNECTED, PUT_TELL, GOODBYE_TELL,
	ADD, ADD_TELL, COMMIT, CONFLICT, PULL, PULL_TELL, REMOVE_FILE, REMOVE_FILE_TELL, COMMIT_TELL, PUSH_RESOLVE, PUSH_RESOLVE_TELL


	}
